### ISSUE TITLE
Cognito lambda tigger for pre token generation

### ISSUE THREAD

**Issue by cenxui** [awslabs/aws-cloudformation-templates#120]
Current cloudformation version seems not provide pre token generation for lambda trigger config

**Comment by cmmeyer** [comment]
Hi @cenxui -- thanks for the feedback. This sounds like a feature request for CloudFormation, rather than an issue with any of the templates in this repo. We do not track service feature requests here so I'm going to close this issue. 

I'll pass this request through internal channels -- this would be implemented by the Cognito team so I'll make sure to route it to them.

**Comment by plusdavid** [comment]
Any update since November? I am also not seeing the Pre Token Generation not working properly with cloudformation.

**Comment by hisham** [comment]
+1
