### ISSUE TITLE
HTTP routing to HTTPS

### ISSUE THREAD

**Issue by fafafariba** [awslabs/aws-cloudformation-templates#65]
This is a question, not an issue per se. What changes you make to this template to redirect HTTP to HTTPS?

**Comment by LRomandine** [comment]
Can you specify which template you are referencing?

**Comment by fafafariba** [comment]
The one here:
https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/services/ECS/FargateLaunchType/services/public-service.yml

I was under the impression you would add something some config to the load balancer.

**Comment by LRomandine** [comment]
I believe you would just need to change the targetgroup since an ALB's listener port is configured in the listener, but then the port it communicates to the contrainers is defined in the targetgroup.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html

Around lines 133-134 in the file you linked.

**Comment by fafafariba** [comment]
As in, change that `Protocol: HTTP` to `HTTPS` ?

**Comment by LRomandine** [comment]
That is part of it yes.  Please read the linked documentation page for more information.  If you need further assistance, please open a support ticket in the AWS console.
